apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ppjv3fqqk-python
  janus-idp.io/tekton: ppjv3fqqk-python
  backstage.io/kubernetes-id: ppjv3fqqk-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ppjv3fqqk-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
