apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ppjv3fqqk-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ppjv3fqqk-python 
  name: ppjv3fqqk-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ppjv3fqqk-python 
